name: covid19swiss data refresh

on: 
  schedule:
    - cron:  '30 */4 * * *'
jobs:
  data_refresh_dev:
    name: covid19swiss dataset refresh dev
    runs-on: ubuntu-18.04 
    container: 
     image:  rkrispin/covid19swiss:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'dev'
      - name: Refresh the data
        run: bash ./data_raw/data_refresh.sh
  data_refresh_master:
    name: covid19swiss dataset refresh master
    runs-on: ubuntu-18.04 
    container: 
     image:  rkrispin/covid19swiss:prod
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'master'
      - name: Refresh the data
        run: bash ./data_raw/data_refresh.sh
